"""Added itens Column in table Pedido

Revision ID: dfcf1ae9dab8
Revises: 4045fabdef29
Create Date: 2026-05-24 17:19:21.826475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcf1ae9dab8'
down_revision: Union[str, Sequence[str], None] = '4045fabdef29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
